name: Update DATA_LOG

on:
  repository_dispatch:
    types: [update_data_log]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write JSON
        run: |
          echo '${{ github.event.client_payload.data }}' > DATA_LOG.json

      - name: Commit
        run: |
          git config --global user.name "automation"
          git config --global user.email "bot@github.com"
          git add DATA_LOG.json
          git commit -m "Update DATA_LOG.json" || echo "No changes"
          git push
